[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clever_todo = "Aamrf9P1xSXV29MHTEaZHgWssVm2maNzJBdxp3rsEMf2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ankit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
